### ISSUE TITLE
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes

### ISSUE THREAD

**Issue by Artur-** [woutervroege/color-picker#1]
It is not possible to create an instance of `<color-picker>` using `document.createElement("color-picker")` as the constructor sets attributes on the element.

The attribute set is `"<style="background: rgb(255, 0, 0); transform: translate(0px, 0px);"></color-picker>"` originating from https://github.com/woutervroege/color-picker/blob/master/color-picker.js#L173 and actually setting the `style` attribute here https://github.com/woutervroege/color-picker/blob/master/color-picker.js#L668

**Comment by woutervroege** [comment]
@Artur- thanks for filing this issue :) However, I cannot seem to reproduce this. Any chance you could provide a snippet?

**Comment by woutervroege** [comment]
@Artur- Edit; got it: Should be fixed now, see v1.0.7
